const flashcardBank = [
  // ==================== NETWORK FUNDAMENTALS (47 cards) ====================
  { id: 1, domain: "Network Fundamentals", subsection: "Network Topologies", term: "Star Topology", definition: "All devices connect to a central device (switch or hub). Failure of central device affects all others, but individual links can fail without affecting others.", example: "Most modern Ethernet networks use star topology" },
  { id: 2, domain: "Network Fundamentals", subsection: "Network Topologies", term: "Bus Topology", definition: "All devices connect to a single cable (backbone). Easy to implement but limited distance and bandwidth; a break in the cable affects the entire network.", example: "Older 10BASE2 coaxial Ethernet networks" },
  { id: 3, domain: "Network Fundamentals", subsection: "Network Topologies", term: "Ring Topology", definition: "Devices connect in a circular fashion. Data travels around the ring until it reaches the destination. Can be disrupted by single link failure.", example: "Token Ring networks" },
  { id: 4, domain: "Network Fundamentals", subsection: "Network Topologies", term: "Mesh Topology", definition: "Devices connect to multiple other devices. Provides redundancy - if one path fails, traffic can take another route. Full mesh connects all devices to all others.", example: "Internet backbone uses mesh topology" },
  { id: 5, domain: "Network Fundamentals", subsection: "Network Topologies", term: "Hybrid Topology", definition: "Combination of two or more topology types. Most networks today are hybrid (e.g., star-bus, star-ring).", example: "Corporate network combining star topology for access and backbone mesh" },
  
  { id: 6, domain: "Network Fundamentals", subsection: "OSI Model", term: "Physical Layer (Layer 1)", definition: "Transmits raw bit streams over physical medium. Deals with cables, connectors, electrical signals, hubs, repeaters.", example: "Ethernet cables (Cat5e, Cat6), fiber optics, RJ-45 ports" },
  { id: 7, domain: "Network Fundamentals", subsection: "OSI Model", term: "Data Link Layer (Layer 2)", definition: "Provides node-to-node transfer. Handles framing, physical addressing (MAC), error detection, flow control. Switches operate at this layer.", example: "MAC addresses, Ethernet frames, LLC, PPP" },
  { id: 8, domain: "Network Fundamentals", subsection: "OSI Model", term: "Network Layer (Layer 3)", definition: "Provides logical addressing (IP) and routing. Handles packet forwarding between networks. Routers operate at this layer.", example: "IP addresses, ICMP, IPsec, IP routing" },
  { id: 9, domain: "Network Fundamentals", subsection: "OSI Model", term: "Transport Layer (Layer 4)", definition: "Provides end-to-end communication. Manages segmentation, flow control, error recovery. Uses ports to identify specific applications.", example: "TCP (reliable), UDP (fast/unreliable), port numbers" },
  { id: 10, domain: "Network Fundamentals", subsection: "OSI Model", term: "Session Layer (Layer 5)", definition: "Manages sessions between applications. Establishes, maintains, and terminates connections. Handles authentication.", example: "NetBIOS, RPC, PPTP" },
  { id: 11, domain: "Network Fundamentals", subsection: "OSI Model", term: "Presentation Layer (Layer 6)", definition: "Handles data translation, encryption, compression. Ensures data from application layer is readable by network.", example: "JPEG, GIF, TLS/SSL, encryption, ASCII" },
  { id: 12, domain: "Network Fundamentals", subsection: "OSI Model", term: "Application Layer (Layer 7)", definition: "Closest to user. Provides network services to end-user applications. Interface between user and network.", example: "HTTP, FTP, DNS, SMTP, Telnet" },
  { id: 13, domain: "Network Fundamentals", subsection: "OSI Model", term: "PDU (Protocol Data Unit)", definition: "Data at each OSI layer has a specific name: Bits (L1), Frames (L2), Packets (L3), Segments (L4), Data (L5-7).", example: "Switch port operates at L2, receives frames; Router operates at L3, routes packets" },
  
  { id: 14, domain: "Network Fundamentals", subsection: "TCP/IP Model", term: "TCP/IP 4-Layer Model", definition: "Network Access (Link), Internet, Transport, Application. Simpler than OSI but maps to it. Foundation of internet communication.", example: "HTTP -> Application, TCP -> Transport, IP -> Internet, Ethernet -> Network Access" },
  { id: 15, domain: "Network Fundamentals", subsection: "TCP/IP Model", term: "TCP (Transmission Control Protocol)", definition: "Connection-oriented, reliable protocol. Provides error recovery, flow control, sequencing. Three-way handshake establishes connection.", example: "SSH, Telnet, HTTP, HTTPS, FTP" },
  { id: 16, domain: "Network Fundamentals", subsection: "TCP/IP Model", term: "UDP (User Datagram Protocol)", definition: "Connectionless, unreliable protocol. No handshake, no error recovery, no flow control. Faster but less reliable than TCP.", example: "DNS, DHCP, SNMP, TFTP, VoIP" },
  { id: 17, domain: "Network Fundamentals", subsection: "TCP/IP Model", term: "Three-Way Handshake", definition: "TCP connection establishment: SYN -> SYN-ACK -> ACK. Ensures both endpoints are ready to communicate.", example: "Client sends SYN, Server responds SYN-ACK, Client sends ACK" },
  { id: 18, domain: "Network Fundamentals", subsection: "TCP/IP Model", term: "TCP Flags", definition: "Control bits in TCP header: SYN (sync), ACK (acknowledge), FIN (finish), RST (reset), PSH (push), URG (urgent).", example: "SYN flag initiates connection; RST resets broken connection" },
  
  { id: 19, domain: "Network Fundamentals", subsection: "Ethernet", term: "CSMA/CD", definition: "Carrier Sense Multiple Access with Collision Detection. Used in half-duplex Ethernet. Devices listen before transmitting; if collision detected, all stop and wait random time.", example: "Old 10BASE-T/100BASE-TX half-duplex networks using hubs" },
  { id: 20, domain: "Network Fundamentals", subsection: "Ethernet", term: "CSMA/CA", definition: "Carrier Sense Multiple Access with Collision Avoidance. Used in wireless networks (Wi-Fi). Devices send RTS/CTS to avoid collisions.", example: "802.11 wireless networks" },
  { id: 21, domain: "Network Fundamentals", subsection: "Ethernet", term: "MAC Address", definition: "Media Access Control address. 48-bit (6 bytes) hardware address burned into NIC. First 24 bits = OUI (vendor), last 24 bits = unique identifier.", example: "00:1A:2B:3C:4D:5E or 001A.2B3C.4D5E (Cisco format)" },
  { id: 22, domain: "Network Fundamentals", subsection: "Ethernet", term: "Ethernet Frame", definition: "Data link layer unit. Structure: Preamble (7) + SFD (1) + Dest MAC (6) + Src MAC (6) + Type/Length (2) + Data (46-1500) + FCS (4).", example: "Type 0x0800 = IPv4, 0x86DD = IPv6, 0x0806 = ARP" },
  { id: 23, domain: "Network Fundamentals", subsection: "Ethernet", term: "Full Duplex", definition: "Simultaneous bidirectional communication. No collisions, CSMA/CD disabled. Requires point-to-point link, typically with switches.", example: "Modern 1Gbps Ethernet uses full duplex" },
  { id: 24, domain: "Network Fundamentals", subsection: "Ethernet", term: "Half Duplex", definition: "One-way communication at a time. Uses CSMA/CD. Found in older networks with hubs.", example: "10Mbps networks connected via hub" },
  
  { id: 25, domain: "Network Fundamentals", subsection: "IP Addressing", term: "IPv4 Address", definition: "32-bit address divided into 4 octets (0-255). Classful: A (1-126), B (128-191), C (192-223), D (224-239-multicast), E (240-255-reserved).", example: "192.168.1.1, 10.0.0.1" },
  { id: 26, domain: "Network Fundamentals", subsection: "IP Addressing", term: "Private IPv4 Addresses", definition: "RFC 1918 addresses not routed on internet: 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16. Used in LANs, requires NAT for internet access.", example: "192.168.1.1 (home router LAN), 10.10.10.10 (enterprise)" },
  { id: 27, domain: "Network Fundamentals", subsection: "IP Addressing", term: "Special IPv4 Addresses", definition: "127.0.0.0/8 = Loopback, 0.0.0.0 = Default route/this host, 255.255.255.255 = Limited broadcast, 169.254.0.0/16 = Link-local (APIPA).", example: "ping 127.0.0.1 tests local TCP/IP stack" },
  { id: 28, domain: "Network Fundamentals", subsection: "IP Addressing", term: "IPv6 Address", definition: "128-bit address written as 8 groups of 4 hex digits. Examples: FE80::1 (link-local), 2001:DB8::1 (documentation), ::1 (loopback).", example: "2001:0DB8:ACAD:0001:0000:0000:0000:0001 or 2001:DB8:ACAD:1::1" },
  { id: 29, domain: "Network Fundamentals", subsection: "IP Addressing", term: "IPv6 Address Types", definition: "Unicast (single interface), Multicast (group), Anycast (nearest). No broadcast. Link-local (FE80::/10) auto-configured on interface.", example: "Global unicast starts with 2000::/3" },
  
  { id: 30, domain: "Network Fundamentals", subsection: "Subnetting", term: "Subnet Mask", definition: "Determines network vs host portion. /24 = 255.255.255.0 (256 hosts), /16 = 255.255.0.0 (65,536 hosts), /8 = 255.0.0.0 (16M hosts).", example: "192.168.1.10/26 = Network 192.168.1.0, range .0-.63" },
  { id: 31, domain: "Network Fundamentals", subsection: "Subnetting", term: "VLSM (Variable Length Subnet Mask)", definition: "Subnets of different sizes within same network. Allows efficient IP allocation by matching subnet size to host requirement.", example: "Use /30 for point-to-point links (4 IPs), /24 for user VLANs" },
  { id: 32, domain: "Network Fundamentals", subsection: "Subnetting", term: "Supernetting", definition: "Combining smaller networks into larger address block. Summarizes routes. Inverse of subnetting.", example: "192.168.0.0/22 summarizes 192.168.0.0-3.0/24" },
  { id: 33, domain: "Network Fundamentals", subsection: "Subnetting", term: "CIDR (Classless Inter-Domain Routing)", definition: "IP addressing scheme replacing classful addressing. Notation: /prefix (e.g., 192.168.1.0/24). Allows flexible subnet sizing.", example: "10.0.0.0/8 is CIDR notation for Class A network" },
  
  { id: 34, domain: "Network Fundamentals", subsection: "ARP", term: "ARP (Address Resolution Protocol)", definition: "Maps IP addresses to MAC addresses. Host broadcasts ARP request: Who has IP x.x.x.x? Target responds with its MAC.", example: "arp -a shows ARP cache on Windows/Linux" },
  { id: 35, domain: "Network Fundamentals", subsection: "ARP", term: "ARP Types", definition: "Request (broadcast): Who has target IP? Reply (unicast): I have target IP, here's my MAC. Gratuitous ARP: announces IP/MAC mapping to update caches.", example: "Gratuitous ARP used when NIC changes MAC or for duplicate IP detection" },
  
  { id: 36, domain: "Network Fundamentals", subsection: "ICMP", term: "ICMP (Internet Control Message Protocol)", definition: "Network layer protocol for error reporting and diagnostics. Used by ping, traceroute. Type/Code identifies message purpose.", example: "Type 0 = Echo Reply, Type 8 = Echo Request, Type 3 = Destination Unreachable" },
  { id: 37, domain: "Network Fundamentals", subsection: "ICMP", term: "Ping", definition: "Uses ICMP Echo Request/Reply to test connectivity. Measures round-trip time (RTT). Does not use TCP/UDP.", example: "ping 8.8.8.8 tests connectivity to Google DNS" },
  
  { id: 38, domain: "Network Fundamentals", subsection: "Cabling", term: "UTP (Unshielded Twisted Pair)", definition: "Copper cable with twisted pairs. Categories: Cat5 (100Mbps), Cat5e (1Gbps), Cat6 (10Gbps), Cat6a (10Gbps/100m), Cat7/8 (40Gbps).", example: "Straight-through used for host-to-switch; crossover for host-to-host" },
  { id: 39, domain: "Network Fundamentals", subsection: "Cabling", term: "Fiber Optic Cable", definition: "Uses light to transmit data. Single-mode (long distance, 100km+), Multimode (shorter, up to 2km). Immune to EMI.", example: "LC, SC, ST connectors; SMF typically used for ISP connections" },
  { id: 40, domain: "Network Fundamentals", subsection: "Cabling", term: "Ethernet Cable Pinouts", definition: "T568A and T568B are wire color standards. Straight-through uses same standard both ends; crossover uses different standards.", example: "Crossover: pins 1<->3, 2<->6 (older use, now auto-MDI/MDIX)" },
  
  { id: 41, domain: "Network Fundamentals", subsection: "Collisions/Broadcast Domains", term: "Collision Domain", definition: "Network segment where collisions occur. Hubs = single collision domain. Switches = each port is separate collision domain.", example: "Connecting 4 hosts to a hub = 1 collision domain. Connecting to switch = 4 separate domains" },
  { id: 42, domain: "Network Fundamentals", subsection: "Collisions/Broadcast Domains", term: "Broadcast Domain", definition: "Group of devices receiving broadcast frames. Routers/LAYER3 switches break broadcast domains. Switches forward broadcasts within VLAN.", example: "Default VLAN 1 on switch = one broadcast domain per VLAN" },
  
  { id: 43, domain: "Network Fundamentals", subsection: "Network Devices", term: "Hub", definition: "Layer 1 device. Repeats incoming signals to all ports. Creates single collision domain. Obsolete, replaced by switches.", example: "10BASE-T hub - all traffic goes to all ports" },
  { id: 44, domain: "Network Fundamentals", subsection: "Network Devices", term: "Switch", definition: "Layer 2 device. Uses MAC table to forward frames to specific port. Creates separate collision domains. Learns MAC addresses dynamically.", example: "switch# show mac address-table" },
  { id: 45, domain: "Network Fundamentals", subsection: "Network Devices", term: "Router", definition: "Layer 3 device. Routes packets between networks using IP addresses. Breaks broadcast domains. Uses routing tables.", example: "router# show ip route" },
  { id: 46, domain: "Network Fundamentals", subsection: "Network Devices", term: "Firewall", definition: "Security device controlling traffic based on rules. Can operate at multiple layers. Stateful inspection tracks connections.", example: "ASA, Firepower, or Zone-Based Policy Firewall" },
  { id: 47, domain: "Network Fundamentals", subsection: "Network Devices", term: "Access Point (AP)", definition: "Wireless device allowing Wi-Fi clients to connect to wired network. Bridges wireless to Ethernet.", example: "Cisco Aironet, Meraki MR access points" },

  // ==================== NETWORK ACCESS (37 cards) ====================
  { id: 48, domain: "Network Access", subsection: "VLANs", term: "VLAN (Virtual LAN)", definition: "Logical segmentation of switch into separate broadcast domains. Default VLAN is 1. VLANs 1002-1005 reserved for legacy.", example: "switch(config)# vlan 10; switch(config-vlan)# name SALES" },
  { id: 49, domain: "Network Access", subsection: "VLANs", term: "VLAN Tagging", definition: "Adding VLAN ID to frames to identify which VLAN traffic belongs to. 802.1Q adds 4-byte tag in Ethernet header.", example: "Tagged frames traverse trunk links between switches" },
  { id: 50, domain: "Network Access", subsection: "VLANs", term: "Native VLAN", definition: "VLAN that receives untagged traffic on trunk port. Default is VLAN 1. Should be changed for security.", example: "switch(config-if)# switchport trunk native vlan 999" },
  { id: 51, domain: "Network Access", subsection: "VLANs", term: "Voice VLAN", definition: "Separate VLAN for VoIP traffic. Uses CDP to communicate VLAN to IP phones. Typically uses 802.1Q tagging.", example: "switch(config-if)# switchport voice vlan 20" },
  
  { id: 52, domain: "Network Access", subsection: "Trunking", term: "802.1Q Trunking", definition: "Adds VLAN tag to frames. 4-byte tag includes TPID (0x8100) and TCI (VLAN ID + priority). Supports 4096 VLANs.", example: "switch(config-if)# switchport mode trunk" },
  { id: 53, domain: "Network Access", subsection: "Trunking", term: "DTP (Dynamic Trunking Protocol)", definition: "Cisco proprietary protocol that negotiates trunk formation. Modes: dynamic auto, dynamic desirable, trunk, access, nonegotiate.", example: "switch(config-if)# switchport mode dynamic auto" },
  { id: 54, domain: "Network Access", subsection: "Trunking", term: "Allowed VLANs on Trunk", definition: "By default, all VLANs allowed on trunk. Can restrict using allowed vlan list for security and reduced VLAN propagation.", example: "switch(config-if)# switchport trunk allowed vlan 10,20,30" },
  
  { id: 55, domain: "Network Access", subsection: "EtherChannel", term: "EtherChannel", definition: "Bundles multiple physical links into one logical link for increased bandwidth and redundancy. Load balances across links.", example: "PAgP (Cisco), LACP (IEEE 802.3AD)" },
  { id: 56, domain: "Network Access", subsection: "EtherChannel", term: "LACP (Link Aggregation Control Protocol)", definition: "IEEE standard (802.3AD) for EtherChannel. Modes: active, passive. Negotiates with neighbor.", example: "switch(config-if)# channel-group 1 mode active" },
  { id: 57, domain: "Network Access", subsection: "EtherChannel", term: "PAgP (Port Aggregation Protocol)", definition: "Cisco proprietary EtherChannel protocol. Modes: auto, desirable, on. Only works between Cisco devices.", example: "switch(config-if)# channel-group 1 mode desirable" },
  { id: 58, domain: "Network Access", subsection: "EtherChannel", term: "EtherChannel Load Balancing", definition: "Traffic distributed across member links using hash algorithm based on source/destination MAC, IP, or port.", example: "switch(config)# port-channel load-balance src-dst-ip" },
  
  { id: 59, domain: "Network Access", subsection: "Spanning Tree", term: "STP (Spanning Tree Protocol)", definition: "Layer 2 loop prevention protocol. Blocks redundant paths to create loop-free topology. Uses BPDUs to elect root bridge.", example: "802.1D original STP" },
  { id: 60, domain: "Network Access", subsection: "Spanning Tree", term: "Root Bridge", definition: "Bridge with lowest Bridge ID (priority + MAC). All ports in forwarding state. Elected via BPDU exchange.", example: "switch(config)# spanning-tree vlan 1 root primary" },
  { id: 61, domain: "Network Access", subsection: "Spanning Tree", term: "BPDU (Bridge Protocol Data Unit)", definition: "Messages exchanged between switches for STP calculation. Contains Bridge ID, port costs, port IDs.", example: "Configuration BPDU (topology change), TCN BPDU (notification)" },
  { id: 62, domain: "Network Access", subsection: "Spanning Tree", term: "STP Port States", definition: "Disabled (no STP), Blocking (listening, 20 sec), Listening (15 sec), Learning (15 sec), Forwarding. 50 sec default to forward.", example: "Rapid PVST+ reduces to seconds using proposal/agreement" },
  { id: 63, domain: "Network Access", subsection: "Spanning Tree", term: "Rapid PVST+", definition: "Cisco implementation of rapid STP. Creates instance per VLAN. Uses PortFast, UplinkFast, BackboneFast for convergence.", example: "switch(config)# spanning-tree mode rapid-pvst" },
  { id: 64, domain: "Network Access", subsection: "Spanning Tree", term: "PortFast", definition: "STP feature that bypasses listening/learning states. Used for access ports connected to end devices (PCs, servers).", example: "switch(config-if)# spanning-tree portfast" },
  { id: 65, domain: "Network Access", subsection: "Spanning Tree", term: "BPDU Guard", definition: "Security feature that disables port if BPDU received. Used on PortFast ports to prevent switch insertion attacks.", example: "switch(config-if)# spanning-tree bpduguard enable" },
  
  { id: 66, domain: "Network Access", subsection: "Wireless", term: "802.11 Standards", definition: "Wi-Fi standards: a (5GHz/54Mbps), b (2.4GHz/11Mbps), g (2.4GHz/54Mbps), n (2.4/5GHz/600Mbps), ac (5GHz/3.4Gbps), ax (Wi-Fi 6).", example: "802.11ac Wave 2 supports MU-MIMO" },
  { id: 67, domain: "Network Access", subsection: "Wireless", term: "SSID (Service Set Identifier)", definition: "Network name for Wi-Fi. Broadcast in beacons (can be hidden). Clients associate using SSID and password.", example: "Corporate_WiFi, Guest_Network" },
  { id: 68, domain: "Network Access", subsection: "Wireless", term: "WPA3/WPA2 Security", definition: "WPA3-Personal uses SAE for stronger password protection. WPA2-Enterprise uses 802.1X with RADIUS. WPA2-PSK uses pre-shared key.", example: "WPA3-SAE, WPA2-AES, WPA-TKIP" },
  { id: 69, domain: "Network Access", subsection: "Wireless", term: "CAPWAP (Control and Provisioning of Wireless Access Points)", definition: "Protocol for central controller to manage APs. Tunnels traffic between AP and controller. Split-MAC architecture.", example: "Cisco WLC manages lightweight APs via CAPWAP" },
  { id: 70, domain: "Network Access", subsection: "Wireless", term: "RF (Radio Frequency)", definition: "Wireless transmission using electromagnetic waves. 2.4GHz (longer range, more interference), 5GHz (shorter range, less interference).", example: "Channel selection important - non-overlapping channels: 1, 6, 11" },
  { id: 71, domain: "Network Access", subsection: "Wireless", term: "Antenna Types", definition: "Omni-directional (360 deg), directional (focused beam), Yagi, patch, parabolic. Gain measured in dBi.", example: "Omni for central AP, directional for point-to-point" },
  
  { id: 72, domain: "Network Access", subsection: "Inter-VLAN Routing", term: "Inter-VLAN Routing", definition: "Routing between VLANs. Requires Layer 3 device (router or Layer 3 switch). Each VLAN needs IP subnet.", example: "Router on a stick: subinterfaces for each VLAN" },
  { id: 73, domain: "Network Access", subsection: "Inter-VLAN Routing", term: "Router on a Stick", definition: "Single physical router interface with multiple subinterfaces, each in different VLAN. Trunk link connects router to switch.", example: "Router(config-subif)# encapsulation dot1Q 10" },
  { id: 74, domain: "Network Access", subsection: "Inter-VLAN Routing", term: "Layer 3 Switch", definition: "Switch with routing capability (MLS - Multi-Layer Switch). Uses ASICs for fast switching. SVI interfaces for VLAN routing.", example: "switch(config)# ip routing; switch(config)# interface vlan 10" },
  
  { id: 75, domain: "Network Access", subsection: "Port Security", term: "Port Security", definition: "Restricts input to port based on MAC addresses. Limits number of MAC addresses, defines allowed MACs. Violation actions: protect, restrict, shutdown.", example: "switch(config-if)# switchport port-security" },
  { id: 76, domain: "Network Access", subsection: "Port Security", term: "Port Security Violation Actions", definition: "Protect (drops traffic, no notification), Restrict (drops + logs), Shutdown (err-disable port).", example: "switch(config-if)# switchport port-security violation restrict" },
  { id: 77, domain: "Network Access", subsection: "Port Security", term: "Sticky MAC Addresses", definition: "Dynamically learned MAC addresses that are converted to static and added to running config. Survives port flap.", example: "switch(config-if)# switchport port-security mac-address sticky" },
  { id: 78, domain: "Network Access", subsection: "Port Security", term: "MAC Address Aging", definition: "Time before unused MAC addresses removed from table. Absolute (strict time) or Inactivity (only if not used).", example: "switch(config)# mac address-table aging-time 150" },
  { id: 79, domain: "Network Access", subsection: "Port Security", term: "DHCP Snooping", definition: "Layer 2 security feature. Filters unauthorized DHCP servers. Builds binding table of IP-to-MAC.", example: "switch(config)# ip dhcp snooping" },
  { id: 80, domain: "Network Access", subsection: "Port Security", term: "ARP Inspection (DAI)", definition: "Dynamic ARP Inspection. Validates ARP packets against DHCP snooping binding table. Prevents ARP spoofing.", example: "switch(config)# ip arp inspection vlan 10" },
  { id: 81, domain: "Network Access", subsection: "Port Security", term: "IP Source Guard", definition: "Uses DHCP snooping binding table to filter IP traffic. Prevents IP spoofing attacks on access ports.", example: "switch(config)# ip verify source" },
  { id: 82, domain: "Network Access", subsection: "Port Security", term: "Storm Control", definition: "Monitors and suppresses broadcast, multicast, unicast storms. Shuts down or filters when threshold exceeded.", example: "switch(config-if)# storm-control broadcast level 10" },
  { id: 83, domain: "Network Access", subsection: "Port Security", term: "Loop Guard", definition: "Prevents loops caused by unidirectional links. Monitors BPDUs; moves to loop-inconsistent state if stopped.", example: "switch(config)# spanning-tree loopguard default" },
  { id: 84, domain: "Network Access", subsection: "Port Security", term: "Root Guard", definition: "Prevents external switch from becoming root bridge. Configured on ports where non-root switches should not connect.", example: "switch(config-if)# spanning-tree guard root" },

  // ==================== IP CONNECTIVITY (48 cards) ====================
  { id: 85, domain: "IP Connectivity", subsection: "Routing Fundamentals", term: "Routing", definition: "Process of forwarding packets from source to destination based on IP address. Uses routing table to determine best path.", example: "router determines next hop based on destination IP" },
  { id: 86, domain: "IP Connectivity", subsection: "Routing Fundamentals", term: "Routing Table", definition: "Contains routes to networks. Columns: Network, Next Hop, Interface, Metric/AD. Populated by connected, static, or dynamic routes.", example: "show ip route" },
  { id: 87, domain: "IP Connectivity", subsection: "Routing Fundamentals", term: "Administrative Distance (AD)", definition: "Trustworthiness of route source. Lower = preferred. Connected=0, Static=1, EIGRP=90, OSPF=110, RIP=120. Directly connected preferred over default route.", example: "ip route 0.0.0.0 0.0.0.0 192.168.1.1 has AD of 1" },
  { id: 88, domain: "IP Connectivity", subsection: "Routing Fundamentals", term: "Longest Prefix Match", definition: "Router uses most specific route (longest subnet mask) when multiple routes match destination.", example: "Packet to 10.1.1.10 matches both 10.0.0.0/8 and 10.1.0.0/16; /16 wins" },
  
  { id: 89, domain: "IP Connectivity", subsection: "Static Routing", term: "Static Route", definition: "Manually configured route. Used for specific networks, default routes, stub networks. Low AD (1) beats dynamic protocols.", example: "ip route 192.168.10.0 255.255.255.0 10.1.1.1" },
  { id: 90, domain: "IP Connectivity", subsection: "Static Routing", term: "Default Route", definition: "Gateway of last resort. Used when no specific route matches. 0.0.0.0/0 matches all networks.", example: "ip route 0.0.0.0 0.0.0.0 192.168.1.1" },
  { id: 91, domain: "IP Connectivity", subsection: "Static Routing", term: "Floating Static Route", definition: "Backup static route with higher AD than dynamic routing. Becomes active only when primary route fails.", example: "ip route 10.0.0.0 255.0.0.0 192.168.1.2 200 (AD 200)" },
  
  { id: 92, domain: "IP Connectivity", subsection: "OSPF", term: "OSPF (Open Shortest Path First)", definition: "Link-state IGP. Uses Dijkstra SPF algorithm. Scalable, hierarchical design. Uses cost as metric.", example: "router ospf 1; network 10.0.0.0 0.0.0.255 area 0" },
  { id: 93, domain: "IP Connectivity", subsection: "OSPF", term: "OSPF Areas", definition: "Hierarchical OSPF design. Area 0 = backbone. All areas connect to Area 0. Reduces LSDB size, improves convergence.", example: "ABR connects Area 1 to Area 0" },
  { id: 94, domain: "IP Connectivity", subsection: "OSPF", term: "OSPF Router Types", definition: "Internal (all interfaces in one area), ABR (between areas), ASBR (connects to other AS), Backbone (Area 0).", example: "ABR has LSDB for each area" },
  { id: 95, domain: "IP Connectivity", subsection: "OSPF", term: "OSPF LSA Types", definition: "Type 1: Router LSA (intra-area), Type 2: Network LSA (DR), Type 3: Summary LSA (inter-area), Type 4: ASBR Summary, Type 5: External LSA.", example: "Type 1 floods within area; Type 5 floods entire AS" },
  { id: 96, domain: "IP Connectivity", subsection: "OSPF", term: "OSPF Metrics", definition: "Cost = reference bandwidth / interface bandwidth. Lower cost preferred. Can manually set cost on interface.", example: "ip ospf cost 100" },
  { id: 97, domain: "IP Connectivity", subsection: "OSPF", term: "OSPF Neighbor States", definition: "Down, Init, 2-Way (DR/BDR election), Exstart (master/slave), Exchange (DBD), Loading (LSR/LSU), Full.", example: "Full = adjacency formed, LSDB synchronized" },
  { id: 98, domain: "IP Connectivity", subsection: "OSPF", term: "OSPF DR/BDR", definition: "Designated Router and Backup DR reduce adjacencies on multi-access networks (Ethernet). All others become DROTHER.", example: "Highest Router ID wins DR election" },
  { id: 99, domain: "IP Connectivity", subsection: "OSPF", term: "OSPF Configuration", definition: "Enable OSPF, define networks with wildcards and area, set priority, authentication, Hello/Dead timers.", example: "router ospf 1; network 10.1.1.0 0.0.0.255 area 0" },
  { id: 100, domain: "IP Connectivity", subsection: "OSPF", term: "OSPFv3", definition: "OSPF for IPv6. Uses IPv6 transport. Supports multiple instances per link. Uses link-local addresses for next-hop.", example: "ipv6 router ospf 1" },
  { id: 101, domain: "IP Connectivity", subsection: "OSPF", term: "OSPF Router ID", definition: "32-bit identifier for OSPF router. Highest loopback or interface IP selected if not manually configured.", example: "router-id 1.1.1.1" },
  { id: 102, domain: "IP Connectivity", subsection: "OSPF", term: "OSPF Hello/Dead Timers", definition: "Hello (default 10s, 30s for NBMA), Dead (default 40s, 120s for NBMA). Must match for adjacency.", example: "ip ospf hello-interval 10 dead-interval 40" },
  { id: 103, domain: "IP Connectivity", subsection: "OSPF", term: "OSPF Authentication", definition: "Plain text (Type 1) or MD5 (Type 2) authentication. Protects against rogue OSPF routers.", example: "area 0 authentication message-digest" },
  
  { id: 104, domain: "IP Connectivity", subsection: "EIGRP", term: "EIGRP (Enhanced Interior Gateway Protocol)", definition: "Cisco proprietary hybrid protocol. Uses DUAL algorithm for loop-free paths. Fast convergence. Metrics: bandwidth, delay, load, reliability.", example: "router eigrp 1" },
  { id: 105, domain: "IP Connectivity", subsection: "EIGRP", term: "EIGRP Metrics", definition: "K values determine metric components: K1=Bandwidth, K2=Load, K3=Delay, K4=Reliability, K5=MTU. Default: K1=1, K2=0, K3=1, K4=0, K5=0.", example: "metric weights K1=1 K2=0 K3=1 K4=0 K5=0" },
  { id: 106, domain: "IP Connectivity", subsection: "EIGRP", term: "EIGRP Successor/Feasible Successor", definition: "Successor = best route (lowest metric). Feasible Successor = backup route meeting feasibility condition (FD > RD of successor).", example: "show ip eigrp topology" },
  { id: 107, domain: "IP Connectivity", subsection: "EIGRP", term: "EIGRP Tables", definition: "Neighbor Table (adjacencies), Topology Table (all routes), Routing Table (best routes). Uses RTP for reliable delivery.", example: "show ip eigrp neighbors, show ip eigrp topology" },
  { id: 108, domain: "IP Connectivity", subsection: "EIGRP", term: "EIGRP Configuration", definition: "AS number must match for neighbors. Networks defined with wildcards. Passive interface disables EIGRP on that interface.", example: "router eigrp 1; network 10.0.0.0 0.255.255.255" },
  { id: 109, domain: "IP Connectivity", subsection: "EIGRP", term: "EIGRP Stub", definition: "Limits EIGRP queries, improves stability. Stub router advertises connected/summary routes only. Used in hub-spoke.", example: "router eigrp 1; eigrp stub" },
  { id: 110, domain: "IP Connectivity", subsection: "EIGRP", term: "EIGRP K Values", definition: "Metric formula: [K1*Bandwidth + K2*Bandwidth/(256-Load) + K3*Delay]*[K5/(Reliability+K4)]. Default uses bandwidth+delay only.", example: "Modify with metric weights command" },
  { id: 111, domain: "IP Connectivity", subsection: "EIGRP", term: "EIGRP Variance", definition: "Allows unequal-cost load balancing. Value = Feasible Distance / Successor Distance. Routes with higher metric can be used if within variance.", example: "router eigrp 1; variance 2" },
  
  { id: 112, domain: "IP Connectivity", subsection: "First Hop Redundancy", term: "HSRP (Hot Standby Router Protocol)", definition: "Cisco redundancy protocol. Active/Standby. Virtual IP (gateway). Uses Hello (3 sec), Hold (10 sec). Priority 100 default, higher wins.", example: "standby 1 ip 192.168.1.1" },
  { id: 113, domain: "IP Connectivity", subsection: "First Hop Redundancy", term: "VRRP (Virtual Router Redundancy Protocol)", definition: "IEEE standard (5798). Similar to HSRP. Master/Backup. Virtual IP can be actual router IP (owner).", example: "vrrp 1 ip 192.168.1.1" },
  { id: 114, domain: "IP Connectivity", subsection: "First Hop Redundancy", term: "GLBP (Gateway Load Balancing Protocol)", definition: "Cisco redundancy with load balancing. Multiple routers share gateway IP. Uses AVG (active virtual gateway) and AVF (active virtual forwarder).", example: "glbp 1 ip 192.168.1.1" },
  { id: 115, domain: "IP Connectivity", subsection: "First Hop Redundancy", term: "HSRP States", definition: "Initial, Learn, Listen, Standby, Active. Active router forwards traffic. Standby monitors active, takes over on failure.", example: "show standby brief" },
  { id: 116, domain: "IP Connectivity", subsection: "First Hop Redundancy", term: "HSRP Preempt", definition: "Allows router with higher priority to become Active when it recovers. Must be enabled if desired.", example: "standby 1 preempt" },
  { id: 117, domain: "IP Connectivity", subsection: "First Hop Redundancy", term: "HSRP Authentication", definition: "Simple text or MD5 authentication. Prevents rogue devices from joining HSRP group.", example: "standby 1 authentication md5 key-string cisco" },
  
  { id: 118, domain: "IP Connectivity", subsection: "Routing Table", term: "Administrative Distance Full List", definition: "Connected=0, Static=1, eBGP=20, EIGRP internal=90, OSPF=110, IS-IS=115, RIP=120, EIGRP external=170, iBGP=200, eBGP=20.", example: "Router prefers OSPF (110) over RIP (120)" },
  { id: 119, domain: "IP Connectivity", subsection: "Routing Table", term: "Routing Metrics", definition: "Value used to determine best path. RIP=hop count (max 15), OSPF=cost (bandwidth-based), EIGRP=composite (bandwidth+delay).", example: "Lower metric = better path" },
  { id: 120, domain: "IP Connectivity", subsection: "Routing Table", term: "Equal Cost Load Balancing", definition: "Multiple routes with same AD and metric install in routing table. Traffic distributed across paths. ECMP.", example: "Two equal-cost paths to same destination = load balance" },
  { id: 121, domain: "IP Connectivity", subsection: "Routing Table", term: "Routing Protocol Comparison", definition: "RIP: distance-vector, hop count, max 15 hops. OSPF: link-state, cost metric, hierarchical. EIGRP: hybrid, composite metric, Cisco-only.", example: "Choose based on network size and requirements" },
  { id: 122, domain: "IP Connectivity", subsection: "Routing Table", term: "Passive Interface", definition: "Prevents routing updates from being sent out interface. Still receives updates. Used on LAN interfaces.", example: "router ospf 1; passive-interface default" },
  
  // ==================== IP SERVICES (29 cards) ====================
  { id: 123, domain: "IP Services", subsection: "DHCP", term: "DHCP (Dynamic Host Configuration Protocol)", definition: "Automatically assigns IP addresses, subnet mask, gateway, DNS. Uses DORA process: Discover, Offer, Request, Acknowledge.", example: "ip address dhcp command on client" },
  { id: 124, domain: "IP Services", subsection: "DHCP", term: "DHCP Server Configuration", definition: "Define pool, network, default-router, dns-server, lease time. Exclude specific addresses from assignment.", example: "ip dhcp pool POOL1; network 192.168.1.0 255.255.255.0" },
  { id: 125, domain: "IP Services", subsection: "DHCP", term: "DHCP Relay (Helper Address)", definition: "Forwards DHCP broadcasts across routers. Router receives broadcast, forwards as unicast to DHCP server.", example: "ip helper-address 10.1.1.100" },
  { id: 126, domain: "IP Services", subsection: "DHCP", term: "DHCP Snooping", definition: "Layer 2 security feature. Trusted ports = DHCP server; Untrusted = clients. Builds binding table.", example: "ip dhcp snooping; ip dhcp snooping vlan 10" },
  { id: 127, domain: "IP Services", subsection: "DHCP", term: "DHCP Options", definition: "Additional parameters DHCP can provide: router, dns-server, domain-name, lease time, TFTP server for VoIP.", example: "option 150 ip <tftp-server>" },
  
  { id: 128, domain: "IP Services", subsection: "NAT", term: "NAT (Network Address Translation)", definition: "Translates private IP addresses to public for internet access. Conserves public IP addresses. Types: Static, Dynamic, PAT.", example: "ip nat inside source static 192.168.1.10 203.0.113.5" },
  { id: 129, domain: "IP Services", subsection: "NAT", term: "Static NAT", definition: "One-to-one mapping between private and public IP. Always uses same translation. Useful for inbound access.", example: "ip nat inside source static tcp 192.168.1.10 80 203.0.113.5 80" },
  { id: 130, domain: "IP Services", subsection: "NAT", term: "Dynamic NAT", definition: "Pool of public IPs assigned from available pool. First-come-first-served. No inbound access without static mapping.", example: "ip nat pool POOL 203.0.113.10 203.0.113.20 netmask 255.255.255.0" },
  { id: 131, domain: "IP Services", subsection: "NAT", term: "PAT (Port Address Translation)", definition: "Many-to-one translation using ports. Overload. Most common for home/small business. Uses single public IP.", example: "ip nat inside source list 1 interface gi0/0 overload" },
  { id: 132, domain: "IP Services", subsection: "NAT", term: "NAT Terminology", definition: "Inside Local (private src), Inside Global (public after NAT), Outside Global (public dest), Outside Local (private dest).", example: "Inside = private network, Outside = internet" },
  { id: 133, domain: "IP Services", subsection: "NAT", term: "NAT Commands", definition: "Define inside/outside interfaces. Create translation. Overload for PAT. Verify with show ip nat translations.", example: "ip nat inside; ip nat outside" },
  
  { id: 134, domain: "IP Services", subsection: "NTP", term: "NTP (Network Time Protocol)", definition: "Synchronizes device clocks to UTC. Critical for logging, security (certificates), debugging. Stratum levels 0-15.", example: "ntp server 10.1.1.1" },
  { id: 135, domain: "IP Services", subsection: "NTP", term: "NTP Stratum", definition: "Hierarchy of time sources. Stratum 0 = atomic clock, Stratum 1 = directly connected to stratum 0, Stratum 2 = connected to stratum 1.", example: "Primary NTP servers are stratum 2-3" },
  
  { id: 136, domain: "IP Services", subsection: "DNS", term: "DNS (Domain Name System)", definition: "Translates hostnames to IP addresses. Hierarchical: Root, TLD, Authoritative. Uses port 53.", example: "nslookup www.cisco.com" },
  { id: 137, domain: "IP Services", subsection: "DNS", term: "DNS Record Types", definition: "A (IPv4 address), AAAA (IPv6 address), CNAME (alias), MX (mail), NS (nameserver), PTR (reverse).", example: "A record maps hostname to IPv4" },
  
  { id: 138, domain: "IP Services", subsection: "SNMP", term: "SNMP (Simple Network Management Protocol)", definition: "Monitors network devices. Uses Manager/Agent model. Versions: v1 (cleartext), v2c (bulk), v3 (secure/auth).", example: "snmp-server community string ro" },
  { id: 139, domain: "IP Services", subsection: "SNMP", term: "SNMP Operations", definition: "GET (request value), SET (change value), GETNEXT (iterate), GETBULK (v2/v3), TRAP (unsolicited), INFORM (acknowledged).", example: "Polling: Manager GETs; Traps: Agent sends" },
  { id: 140, domain: "IP Services", subsection: "SNMP", term: "SNMP MIB", definition: "Management Information Base. Hierarchical database of managed objects. OIDs (Object Identifiers) identify variables.", example: "1.3.6.1.2.1.1 sysDescr" },
  
  { id: 141, domain: "IP Services", subsection: "Syslog", term: "Syslog", definition: "Centralized logging for network devices. Severities: Emergency (0), Alert (1), Critical (2), Error (3), Warning (4), Notice (5), Info (6), Debug (7).", example: "logging host 10.1.1.1" },
  { id: 142, domain: "IP Services", subsection: "Syslog", term: "Syslog Facility", definition: "Identifies source of message: local0-7, kernel, user, mail, etc. Helps categorize messages at central server.", example: "logging facility local7" },
  { id: 143, domain: "IP Services", subsection: "Syslog", term: "Syslog Messages", definition: "Format: Timestamp, Facility, Severity, Hostname, Message. Example: %LINK-3-UPDOWN: Interface Gi0/1, changed state to up.", example: "Severity 0-3 should be monitored" },
  
  { id: 144, domain: "IP Services", subsection: "QoS", term: "QoS (Quality of Service)", definition: "Mechanisms to manage bandwidth, delay, jitter, packet loss. Priority queuing, CBWFQ, LLQ, policing, shaping.", example: "voice traffic gets priority over data" },
  { id: 145, domain: "IP Services", subsection: "QoS", term: "QoS Models", definition: "Best Effort (no QoS), Integrated Services (reservations), Differentiated Services (marking/prioritization).", example: "DiffServ uses DSCP values" },
  { id: 146, domain: "IP Services", subsection: "QoS", term: "DSCP (Differentiated Services Code Point)", definition: "6-bit field in IP header for QoS marking. EF (Expedited Forwarding) = 46 for VoIP. AF (Assured Forwarding) classes.", example: "DSCP 46 = EF (voice), DSCP 34 = AF41" },
  
  { id: 147, domain: "IP Services", subsection: "Cloud Concepts", term: "Cloud Computing Models", definition: "IaaS (Infrastructure - VMs), PaaS (Platform - runtime), SaaS (Software - applications).", example: "AWS EC2 = IaaS, Heroku = PaaS, Gmail = SaaS" },
  { id: 148, domain: "IP Services", subsection: "Cloud Concepts", term: "Cloud Deployment Models", definition: "Public (shared resources), Private (dedicated), Hybrid (both connected), Community (shared by specific group).", example: "AWS = public, On-prem = private" },
  { id: 149, domain: "IP Services", subsection: "Cloud Concepts", term: "SD-WAN", definition: "Software-Defined Wide Area Network. Replaces traditional WAN routers with software-based control. Direct internet access at branches.", example: "Cisco Viptela, Meraki SD-WAN" },
  { id: 150, domain: "IP Services", subsection: "Cloud Concepts", term: "Cloud Connectivity", definition: "VPN over internet, Dedicated circuits (MPLS replacement), Cloud exchange, Direct connect.", example: "AWS Direct Connect, Azure ExpressRoute" },
  { id: 151, domain: "IP Services", subsection: "Cloud Concepts", term: "Virtualization vs Cloud", definition: "Virtualization = running multiple VMs on one hardware. Cloud = on-demand resource provisioning with pay-as-you-go.", example: "VMware = virtualization; AWS = cloud" },

  // ==================== SECURITY FUNDAMENTALS (34 cards) ====================
  { id: 152, domain: "Security Fundamentals", subsection: "Security Concepts", term: "CIA Triad", definition: "Confidentiality (prevent unauthorized access), Integrity (prevent modification), Availability (ensure access).", example: "Encryption = confidentiality; Hashing = integrity" },
  { id: 153, domain: "Security Fundamentals", subsection: "Security Concepts", term: "Authentication", definition: "Verifying identity. Methods: Something you know (password), have (token), are (biometric).", example: "Login password, RSA token, fingerprint" },
  { id: 154, domain: "Security Fundamentals", subsection: "Security Concepts", term: "Authorization", definition: "Determines what authenticated user can do. Role-based access control (RBAC) assigns permissions to roles.", example: "User can read but not modify files" },
  { id: 155, domain: "Security Fundamentals", subsection: "Security Concepts", term: "Accounting/Auditing", definition: "Tracks user actions. Logs what was done, when, by whom. Required for compliance and forensics.", example: "Syslog, AAA accounting" },
  { id: 156, domain: "Security Fundamentals", subsection: "Security Concepts", term: "Threats", definition: "Malware (virus, worm, ransomware), Phishing, DoS/DDoS, MITM, SQL Injection, Zero-day.", example: "Worm spreads automatically; Virus requires host" },
  { id: 157, domain: "Security Fundamentals", subsection: "Security Concepts", term: "Vulnerabilities", definition: "Weaknesses in system. Unpatched software, misconfiguration, weak passwords, lack of encryption.", example: "CVE lists known vulnerabilities" },
  { id: 158, domain: "Security Fundamentals", subsection: "Security Concepts", term: "Risk", definition: "Likelihood of threat exploiting vulnerability. Risk = Threat x Vulnerability x Impact.", example: "Mitigate by reducing any factor" },
  
  { id: 159, domain: "Security Fundamentals", subsection: "AAA", term: "AAA (Authentication, Authorization, Accounting)", definition: "Framework for access control. Authentication verifies identity, Authorization sets permissions, Accounting tracks usage.", example: "Tacacs+, RADIUS" },
  { id: 160, domain: "Security Fundamentals", subsection: "AAA", term: "RADIUS", definition: "UDP port 1812 (auth), 1813 (acct). Combines auth/acct. Centralized user database. Used for 802.1X, VPN.", example: "Network access server authenticates to RADIUS" },
  { id: 161, domain: "Security Fundamentals", subsection: "AAA", term: "TACACS+", definition: "TCP port 49. Separates auth, authz, acc. More granular control. Cisco proprietary. Used for device admin.", example: "aaa new-model; tacacs-server host 10.1.1.1" },
  { id: 162, domain: "Security Fundamentals", subsection: "AAA", term: "802.1X", definition: "Port-based network access control. Supplicant (client), Authenticator (switch), Authentication Server (RADIUS).", example: "EAP, PEAP, EAP-TLS" },
  
  { id: 163, domain: "Security Fundamentals", subsection: "ACLs", term: "ACL (Access Control List)", definition: "Ordered list of rules permitting or denying traffic. Processed top-to-bottom, first match wins. Implied deny all at end.", example: "access-list 10 permit host 192.168.1.10" },
  { id: 164, domain: "Security Fundamentals", subsection: "ACLs", term: "Standard ACL", definition: "1-99, 1300-1999. Filters based on source IP only. Place as close to destination as possible.", example: "access-list 10 permit 192.168.1.0 0.0.0.255" },
  { id: 165, domain: "Security Fundamentals", subsection: "ACLs", term: "Extended ACL", definition: "100-199, 2000-2699. Filters based on source, destination, protocol, port. Place close to source.", example: "access-list 101 permit tcp host 10.1.1.1 host 10.2.2.2 eq 80" },
  { id: 166, domain: "Security Fundamentals", subsection: "ACLs", term: "Named ACL", definition: "Uses name instead of number. Allows editing individual lines (replaces numbered). More flexible.", example: "ip access-list extended ACL_NAME" },
  { id: 167, domain: "Security Fundamentals", subsection: "ACLs", term: "ACL Wildcard Mask", definition: "0 = must match, 1 = dont care. Inverse of subnet mask. Used in ACLs and OSPF.", example: "192.168.1.0 0.0.0.255 matches 192.168.1.x" },
  { id: 168, domain: "Security Fundamentals", subsection: "ACLs", term: "ACL Types Summary", definition: "Standard: src only. Extended: src, dst, protocol, port. Named: better management. IPv6:_ipv6 access-list.", example: "Standard placed near dest; Extended near source" },
  
  { id: 169, domain: "Security Fundamentals", subsection: "Port Security", term: "Port Security Features", definition: "MAC limiting, sticky learning, violation actions. Protects against MAC flooding, unauthorized devices.", example: "switchport port-security maximum 3" },
  { id: 170, domain: "Security Fundamentals", subsection: "Port Security", term: "MAC Address Table Security", definition: "MAC flood attack fills table with fake MACs. Mitigate: port security, limit learning, static entries.", example: "Switch clears table when full" },
  { id: 171, domain: "Security Fundamentals", subsection: "Port Security", term: "Switch Security Best Practices", definition: "Disable unused ports, change default VLAN, disable DTP, enable BPDU guard, enable DHCP snooping.", example: "shutdown unused ports immediately" },
  
  { id: 172, domain: "Security Fundamentals", subsection: "DHCP Snooping", term: "DHCP Snooping Detailed", definition: "Untrusted ports = clients only. Trusted ports = DHCP servers, uplinks. Builds binding table of IP/MAC/VLAN/Port.", example: "ip dhcp snooping vlan 10,20" },
  { id: 173, domain: "Security Fundamentals", subsection: "DHCP Snooping", term: "DHCP Attack Types", definition: "Server spoofing (rogue DHCP server), Starvation (exhaust IP pool). Snooping prevents spoofing.", example: "Attacker runs rogue DHCP on network" },
  
  { id: 174, domain: "Security Fundamentals", subsection: "ARP Inspection", term: "Dynamic ARP Inspection", definition: "Validates ARP packets. Checks IP/MAC binding against DHCP snooping table. Drops invalid ARP.", example: "ip arp inspection validate src-mac dst-mac" },
  { id: 175, domain: "Security Fundamentals", subsection: "ARP Inspection", term: "ARP Spoofing Attack", definition: "Attacker sends fake ARP claiming to be gateway. Traffic redirects through attacker. Mitigated by DAI.", example: "Man-in-the-middle attack via ARP" },
  
  { id: 176, domain: "Security Fundamentals", subsection: "VLAN ACLs", term: "VACL (VLAN ACL)", definition: "Applies ACL to VLAN. Filters all traffic entering/leaving VLAN. Does not use routing.", example: "vlan access-map MAP; match ip address ACL" },
  { id: 177, domain: "Security Fundamentals", subsection: "VLAN ACLs", term: "PACL (Port ACL)", definition: "ACL applied directly to switch port. Filters traffic based on Layer 2/3/4 info.", example: "switchport protected or ip access-group on port" },
  
  { id: 178, domain: "Security Fundamentals", subsection: "Firewalls", term: "Firewall Types", definition: "Stateless (packet filtering), Stateful (tracks connections), Application-layer (proxy), Next-gen (UTM).", example: "ASA = stateful; WAF = application-layer" },
  { id: 179, domain: "Security Fundamentals", subsection: "Firewalls", term: "Stateful Inspection", definition: "Tracks connection state (TCP/UDP). Allows return traffic for established connections automatically.", example: "Outbound HTTP allowed, return traffic permitted" },
  { id: 180, domain: "Security Fundamentals", subsection: "Firewalls", term: "Zone-Based Policy Firewall", definition: "Cisco ZBFW. Zones created, interfaces assigned. Policies define traffic between zones. Default: block all.", example: "zone-pair security ZP source INSIDE destination OUTSIDE" },
  { id: 181, domain: "Security Fundamentals", subsection: "Firewalls", term: "Firewall DMZ", definition: "Demilitarized zone. Public-facing servers placed here. Separated from internal network. Limited access to inside.", example: "Web server, DNS in DMZ" },
  
  { id: 182, domain: "Security Fundamentals", subsection: "VPNs", term: "VPN (Virtual Private Network)", definition: "Creates secure tunnel over untrusted network. Types: Site-to-site, Remote access. Encryption protects confidentiality.", example: "SSL VPN, IPsec VPN" },
  { id: 183, domain: "Security Fundamentals", subsection: "VPNs", term: "GRE (Generic Routing Encapsulation)", definition: "Tunneling protocol. Encapsulates multiprotocol traffic. No encryption. Creates virtual point-to-point interface.", example: "tunnel mode gre ip; tunnel destination 10.1.1.1" },
  { id: 184, domain: "Security Fundamentals", subsection: "VPNs", term: "IPsec", definition: "Suite of protocols for secure IP communication. Components: IKE (key exchange), ESP (encryption), AH (authentication).", example: "Crypto map, IPsec tunnel" },
  { id: 185, domain: "Security Fundamentals", subsection: "VPNs", term: "IPsec Modes", definition: "Transport mode = encrypts data only (host-to-host). Tunnel mode = encrypts entire IP header (site-to-site).", example: "Site-to-site uses tunnel mode" },

  // ==================== AUTOMATION & PROGRAMMABILITY (26 cards) ====================
  { id: 186, domain: "Automation", subsection: "SDN", term: "SDN (Software-Defined Networking)", definition: "Separates control plane from data plane. Central controller manages network devices programmatically. OpenFlow is common protocol.", example: "Cisco ACI, OpenDaylight" },
  { id: 187, domain: "Automation", subsection: "SDN", term: "Control Plane vs Data Plane", definition: "Control plane = routing decisions (OSPF, BGP). Data plane = packet forwarding (ASICs). SDN centralizes control plane.", example: "Traditional: distributed control; SDN: centralized" },
  { id: 188, domain: "Automation", subsection: "SDN", term: "Cisco ACI (Application Centric Infrastructure)", definition: "Cisco SDN solution. Uses APIC controller. Policy-based model. Tenant, VRF, Bridge Domain, EPG structure.", example: "APIC manages Nexus 9000 switches" },
  { id: 189, domain: "Automation", subsection: "SDN", term: "VXLAN (Virtual Extensible LAN)", definition: "Encapsulation protocol for Layer 2 over Layer 3. 24-bit VNID supports 16 million segments. Used in data centers.", example: "vxlan vni 10000" },
  
  { id: 190, domain: "Automation", subsection: "REST APIs", term: "REST API", definition: "Representational State Transfer. Uses HTTP methods (GET, POST, PUT, DELETE). JSON or XML format. Stateless client-server.", example: "GET /api/v1/interfaces returns interface info" },
  { id: 191, domain: "Automation", subsection: "REST APIs", term: "HTTP Methods", definition: "GET (read), POST (create), PUT (update/replace), PATCH (partial update), DELETE (remove).", example: "POST /api/vlan creates new VLAN" },
  { id: 192, domain: "Automation", subsection: "REST APIs", term: "API Authentication", definition: "Methods: Basic (base64), Bearer Token (OAuth), API Key. Sent in Authorization header.", example: "Authorization: Bearer <token>" },
  
  { id: 193, domain: "Automation", subsection: "JSON", term: "JSON (JavaScript Object Notation)", definition: "Lightweight data format. Key-value pairs, arrays. Human-readable. Used in REST APIs.", example: "{\"hostname\": \"SW1\", \"vlans\": [10, 20]}" },
  { id: 194, domain: "Automation", subsection: "JSON", term: "JSON vs XML", definition: "JSON: lightweight, native to JS, less verbose. XML: older, supports attributes, self-describing, more overhead.", example: "JSON preferred for modern APIs" },
  
  { id: 195, domain: "Automation", subsection: "XML", term: "XML (Extensible Markup Language)", definition: "Markup language for structured data. Tags are custom. Validated by schema (XSD). Used in YANG/NETCONF.", example: "<interface><name>Gig0/1</name></interface>" },
  { id: 196, domain: "Automation", subsection: "XML", term: "YANG", definition: "Data modeling language for NETCONF. Defines structure of configuration/operational data. Cisco, Juniper models available.", example: "module Cisco-IOS-XE-interfaces" },
  
  { id: 197, domain: "Automation", subsection: "Ansible", term: "Ansible", definition: "Agentless automation tool. Uses SSH. Playbooks in YAML. Idempotent - running multiple times has same result.", example: "ansible-playbook -i inventory site.yml" },
  { id: 198, domain: "Automation", subsection: "Ansible", term: "Ansible Components", definition: "Inventory (hosts), Modules (tasks), Playbooks (plays), Roles (organization).", example: "ios_config module for Cisco" },
  { id: 199, domain: "Automation", subsection: "Ansible", term: "Ansible vs Chef/Puppet", definition: "Ansible: YAML, agentless, push-based. Chef: Ruby DSL, agent required, pull-based. Puppet: Puppet DSL, agent required.", example: "Ansible simpler for network automation" },
  
  { id: 200, domain: "Automation", subsection: "Chef", term: "Chef", definition: "Configuration management tool. Uses Ruby DSL. Agent-based (chef-client). Recipes define configuration, Cookbooks group recipes.", example: "chef-client, knife" },
  { id: 201, domain: "Automation", subsection: "Puppet", term: "Puppet", definition: "Declarative model. Agent-based. Resources define desired state. Catalog compiled by master.", example: "puppet agent -t" },
  { id: 202, domain: "Automation", subsection: "Chef", term: "Puppet vs Chef Comparison", definition: "Puppet: declarative, resources -> catalog. Chef: procedural, recipes execute steps. Both agent-based.", example: "Puppet uses Facter for facts" },
  
  { id: 203, domain: "Automation", subsection: "Cisco DNA Center", term: "Cisco DNA Center", definition: "Centralized management for enterprise networks. Intent-based networking. Assurance, automation, analytics.", example: "DNA Center discovers devices, pushes config" },
  { id: 204, domain: "Automation", subsection: "Cisco DNA Center", term: "DNA Center Features", definition: "Device discovery, template-based configuration, software image management, assurance/monitoring, security analytics.", example: "Command Runner, Compliance Dashboard" },
  { id: 205, domain: "Automation", subsection: "Cisco DNA Center", term: "Intent-Based Networking", definition: "Translate business intent into network policy. Declarative model. System ensures desired state maintained.", example: "Define policy: allow guest access; network implements" },
  
  { id: 206, domain: "Automation", subsection: "Programmability Concepts", term: "NETCONF", definition: "Network management protocol. Uses XML over SSH. Provides create, read, update, delete (CRUD) operations.", example: "NETCONF uses <rpc> and <rpc-reply>" },
  { id: 207, domain: "Automation", subsection: "Programmability Concepts", term: "RESTCONF", definition: "REST-like API for network management. Uses YANG data models. HTTP methods with JSON/XML.", example: "GET /restconf/data/interface" },
  { id: 208, domain: "Automation", subsection: "Programmability Concepts", term: "gNMI (gRPC Network Management Interface)", definition: "Google-developed RPC framework. Uses Protocol Buffers. Efficient, streaming capable. Used in modern network automation.", example: "OpenConfig uses gNMI" },
  { id: 209, domain: "Automation", subsection: "Programmability Concepts", term: "Git", definition: "Version control system. Tracks changes. Branching/merging. Essential for configuration management and automation.", example: "git commit, git push, git pull" },
  { id: 210, domain: "Automation", subsection: "Programmability Concepts", term: "CI/CD for Network", definition: "Continuous Integration/Continuous Deployment. Automated testing, validation, deployment of network changes.", example: "Jenkins pipeline for network config" },
  { id: 211, domain: "Automation", subsection: "Programmability Concepts", term: "Infrastructure as Code (IaC)", definition: "Managing infrastructure via code/versions. Enables version control, testing, repeatability. Tools: Terraform, Ansible.", example: "Terraform defines desired state in HCL" }
];
