#!/usr/bin/env node
/**
 * Batch verify all ExamTopics questions via Gemini AI
 * Run: node scripts/batch-verify.js
 *
 * Rate-limited to 14 requests/minute (Gemini free tier is 15/min)
 * ~1016 questions ÷ 14/min = ~73 minutes
 *
 * Outputs: data/verify-cache.js (loadable in the browser)
 */

const fs = require('fs');
const path = require('path');

const API = 'https://ccna-tutor.rpatino-cw.workers.dev';
const RATE_LIMIT = 14; // requests per minute
const DELAY = Math.ceil(60000 / RATE_LIMIT); // ms between requests

// Load questions
const dataPath = path.join(__dirname, '..', 'data', 'examtopics-data.js');
const dataStr = fs.readFileSync(dataPath, 'utf8');
// Extract the array from the JS file
const match = dataStr.match(/window\.EXAMTOPICS_CARDS\s*=\s*(\[[\s\S]*\]);/);
if (!match) { console.error('Could not parse examtopics-data.js'); process.exit(1); }
const questions = JSON.parse(match[1]);

console.log(`Loaded ${questions.length} questions`);

// Load existing cache (resume support)
const cachePath = path.join(__dirname, '..', 'data', 'verify-cache.js');
let cache = {};
if (fs.existsSync(cachePath)) {
  const cacheStr = fs.readFileSync(cachePath, 'utf8');
  const cacheMatch = cacheStr.match(/window\.VERIFY_CACHE\s*=\s*(\{[\s\S]*\});/);
  if (cacheMatch) {
    try { cache = JSON.parse(cacheMatch[1]); } catch(e) {}
  }
  console.log(`Existing cache: ${Object.keys(cache).length} entries — will skip already verified`);
}

function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }

async function verifyOne(q) {
  const optionsText = q.options.map((o, i) => String.fromCharCode(65 + i) + '. ' + o).join('\n');

  const prompt = `You are a CCNA 200-301 exam expert. Verify this exam question's answer.\n\n` +
    `QUESTION: ${q.question}\n\n` +
    `OPTIONS:\n${optionsText}\n\n` +
    `LISTED CORRECT ANSWER: ${q.correct}\n\n` +
    `Is the listed answer correct? Respond in EXACTLY this JSON format:\n` +
    `{"agree":true/false,"correctAnswer":"X","explanation":"1-2 sentence explanation."}`;

  try {
    const res = await fetch(API, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ message: prompt, history: [] })
    });
    const data = await res.json();
    const reply = data.reply || '';
    const jsonMatch = reply.match(/\{[\s\S]*?\}/);
    if (!jsonMatch) return { agree: true, correctAnswer: q.correct, explanation: 'Could not parse AI response', verified: false };
    const result = JSON.parse(jsonMatch[0]);
    result.verified = true;
    result.ts = new Date().toISOString();
    return result;
  } catch(e) {
    return { agree: true, correctAnswer: q.correct, explanation: 'Error: ' + e.message, verified: false };
  }
}

function saveCache() {
  const total = Object.keys(cache).length;
  const disputed = Object.values(cache).filter(c => !c.agree).length;
  const content = `// Auto-generated by batch-verify.js\n` +
    `// ${total} questions verified, ${disputed} disputed\n` +
    `// Generated: ${new Date().toISOString()}\n` +
    `window.VERIFY_CACHE = ${JSON.stringify(cache, null, 1)};\n`;
  fs.writeFileSync(cachePath, content);
}

async function run() {
  const toVerify = questions.filter(q => !cache[q.id]);
  console.log(`${toVerify.length} questions to verify (${Object.keys(cache).length} already cached)`);

  let done = 0;
  let disputed = 0;

  for (const q of toVerify) {
    const result = await verifyOne(q);
    cache[q.id] = result;
    done++;
    if (!result.agree) disputed++;

    const pct = Math.round((done / toVerify.length) * 100);
    const total = Object.values(cache).filter(c => !c.agree).length;
    process.stdout.write(`\r[${pct}%] ${done}/${toVerify.length} — ${total} disputed total — last: ${q.id} ${result.agree ? '✓' : '✗ → ' + result.correctAnswer}`);

    // Save every 10 questions (resume support)
    if (done % 10 === 0) saveCache();

    // Rate limit
    await sleep(DELAY);
  }

  saveCache();

  const totalDisputed = Object.values(cache).filter(c => !c.agree).length;
  console.log(`\n\nDone! ${Object.keys(cache).length} verified, ${totalDisputed} disputed.`);
  console.log(`Cache saved to: ${cachePath}`);
}

run().catch(console.error);
